### ISSUE TITLE
Error Rendering map on !render fail

### ISSUE THREAD

**Issue by Maaster** [LeaPhant/flowabot#22]
Map: https://osu.ppy.sh/beatmapsets/574824#osu/1217417

Command as it was a recent score: !render fail

Stacktrace:
>[2019-07-16T17:25:17.542Z] render length 4
[2019-07-16T17:25:17.542Z] specified ar undefined
[2019-07-16T17:25:17.781Z] score has no replay
[2019-07-16T17:25:17.799Z] flowabot : Rendering...
process beatmap: 542.014ms
/root/flowabot/renderer/render_worker.js:304
                        position = playfieldPosition(...pos_current);
                                                          ^
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of playfieldPosition
    at /root/flowabot/renderer/render_worker.js:304:36
    at Array.forEach (<anonymous>)
    at processFrame (/root/flowabot/renderer/render_worker.js:143:28)
    at process.on.obj (/root/flowabot/renderer/render_worker.js:422:13)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2019-07-16T17:25:18.886Z] flowabot : Couldn't run command: `Error rendering beatmap`

**Comment by LeaPhant** [comment]
I couldn't reproduce this but I added an additional check in https://github.com/LeaPhant/flowabot/commit/146a5e114fe3ebe2277fc7161501396aa4ee3860 that might prevent it from happening.

**Comment by LeaPhant** [comment]
I managed to reproduce it and it's fixed together with other improvements in https://github.com/LeaPhant/flowabot/commit/6013e8a232f18fddb3b9bb735efd9e348d50f098.
