### ISSUE TITLE
I can't setup bot

### ISSUE THREAD

**Issue by KeepSOBP** [LeaPhant/flowabot#51]
```
ubuntu@flowabot-423651:~/flowabot$ npm run config
............
Discord bot token [none]: <my token>
/home/ubuntu/flowabot/node_modules/discord.js/src/client/ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (/home/ubuntu/flowabot/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/home/ubuntu/flowabot/node_modules/discord.js/src/structures/Guild.js:307:68)
    at GuildCreateHandler.handle (/home/ubuntu/flowabot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (/home/ubuntu/flowabot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/ubuntu/flowabot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/ubuntu/flowabot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/ubuntu/flowabot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/ubuntu/flowabot/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flowabot@1.0.0 config: `node generate-config`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flowabot@1.0.0 config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-04-04T15_16_07_664Z-debug.log
ubuntu@flowabot-423651:~/flowabot$
```

OS : Ubuntu 20.04 LTS
Node Version : 10.24
Discord.js Version : 11.6.4

<details>
  <summary>full logs</summary>

```
ubuntu@flowabot-423651:~/flowabot$ npm i                                                                                                                        > highcharts-export-server@2.0.30 preinstall /home/ubuntu/flowabot/node_modules/highcharts-export-server
> node ./pre.build.js

Preinstall: no tasks to be done, skipping
                                                                                > phantomjs-prebuilt@2.1.14 install /home/ubuntu/flowabot/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [===============================---------] 77%                                Received 22866K total.
Extracting tar contents (via spawned process)
Removing /home/ubuntu/flowabot/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1617549266385/phantomjs-2.1.1-linux-x86_64 -> /home/ubuntu/flowabot/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/ubuntu/flowabot/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> canvas@2.6.1 install /home/ubuntu/flowabot/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[canvas] Success: "/home/ubuntu/flowabot/node_modules/canvas/build/Release/canvas.node" is installed via remote

> diskusage@1.1.3 install /home/ubuntu/flowabot/node_modules/diskusage
> node-gyp rebuild

make: Entering directory '/home/ubuntu/flowabot/node_modules/diskusage/build'
  CXX(target) Release/obj.target/diskusage/src/main.o
In file included from ../../nan/nan.h:56,                                                        from ../src/main.cpp:3:                                        /home/ubuntu/.cache/node-gyp/10.24.0/include/node/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]                                              573 |       (node::addon_register_func) (regfunc),                          \       |                                           ^                             /home/ubuntu/.cache/node-gyp/10.24.0/include/node/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’                                                       607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~                                                         ../src/main.cpp:42:1: note: in expansion of macro ‘NODE_MODULE’                    42 | NODE_MODULE(diskusage, Init)                                                  | ^~~~~~~~~~~                                                             In file included from /home/ubuntu/.cache/node-gyp/10.24.0/include/node/node.h:63,                                                                                               from ../../nan/nan.h:56,                                                        from ../src/main.cpp:3:                                        /home/ubuntu/.cache/node-gyp/10.24.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:                                                                      /home/ubuntu/.cache/node-gyp/10.24.0/include/node/node_object_wrap.h:84:78:   required from here
/home/ubuntu/.cache/node-gyp/10.24.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]                                                                               9502 |                reinterpret_cast<Callback>(callback), type);                   |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     /home/ubuntu/.cache/node-gyp/10.24.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:                                                                        ../../nan/nan_object_wrap.h:65:61:   required from here                         /home/ubuntu/.cache/node-gyp/10.24.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]  CXX(target) Release/obj.target/diskusage/src/diskusage_posix.o
  SOLINK_MODULE(target) Release/obj.target/diskusage.node
  COPY Release/diskusage.node
make: Leaving directory '/home/ubuntu/flowabot/node_modules/diskusage/build'

> highcharts-export-server@2.0.30 install /home/ubuntu/flowabot/node_modules/highcharts-export-server
> node ./build.js


Highcharts Export Server

https://github.com/highcharts/node-export-server

In order to use this application, Highcharts needs to be downloaded and 
embedded. A license is required to use Highcharts if you're a 
for-profit, commercial, outfit. 

The license can be viewed here: https://shop.highsoft.com/media/highsoft/Standard-License-Agreement-6.0.pdf


IF THE DOWNLOAD FAILS:
----------------------

Are you behind a proxy?
See https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables

Are you behind a company firewall?
Try running "npm config set strict-ssl=false" before installing

Agree to the license terms? y/n:  (no) y                                        Select your Highcharts version (e.g. 4.2.2)::  (latest)                         Include Maps? (requires Maps license):  (no)                                    Include Gantt? (requires Gantt license, and >V6.2):  (no)                       Enable styled mode? (requires Highcharts/Highstock 5+ license):  (no)           Include moment.js for date/time handling?:  (no)                                Which CDN would you like to use?:  (https://code.highcharts.com/)               Enable wordcloud support? y/n:  (no)                                            Enable annotations support? y/n:  (no)                                          Pulling Highcharts from CDN (latest)..
   https://code.highcharts.com/stock/highstock.js
   https://code.highcharts.com/highcharts-more.js
   https://code.highcharts.com/modules/exporting.js
   https://code.highcharts.com/highcharts-3d.js
   https://code.highcharts.com/modules/data.js
   https://code.highcharts.com/modules/funnel.js
   https://code.highcharts.com/modules/solid-gauge.js
   https://code.highcharts.com/modules/heatmap.js
   https://code.highcharts.com/modules/treemap.js
   https://code.highcharts.com/modules/sunburst.js
   https://code.highcharts.com/modules/xrange.js
   https://code.highcharts.com/modules/streamgraph.js
   https://code.highcharts.com/modules/sankey.js
   https://code.highcharts.com/modules/tilemap.js
   https://code.highcharts.com/modules/histogram-bellcurve.js
   https://code.highcharts.com/modules/bullet.js
   https://code.highcharts.com/modules/organization.js
   https://code.highcharts.com/modules/funnel3d.js
   https://code.highcharts.com/modules/pyramid3d.js
   https://code.highcharts.com/modules/dependency-wheel.js
   https://code.highcharts.com/modules/item-series.js
   https://code.highcharts.com/modules/timeline.js
   https://code.highcharts.com/modules/pareto.js
   https://code.highcharts.com/modules/coloraxis.js
   https://code.highcharts.com/modules/venn.js
   https://code.highcharts.com/modules/dumbbell.js
   https://code.highcharts.com/modules/lollipop.js
Creating export template export..
All done! Happy charting!
For documentation, see https://github.com/highcharts/node-export-server

> core-js@2.6.12 postinstall /home/ubuntu/flowabot/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> highcharts-export-server@2.0.30 postinstall /home/ubuntu/flowabot/node_modules/highcharts-export-server
> node ./post.build.js

added 440 packages from 326 contributors and audited 441 packages in 127.76s    
17 packages are looking for funding
  run `npm fund` for details

found 19 vulnerabilities (8 low, 6 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
ubuntu@flowabot-423651:~/flowabot$ npm run config                               
> flowabot@1.0.0 config /home/ubuntu/flowabot
> node generate-config


-----------------------------------------------
Welcome to the flowabot configuration wizard 🧙‍
-----------------------------------------------

If you press enter without entering anything it will choose the default value in the [brackets]‍

Command prefix [!]: -

Enable debug messages (yes/no) [yes]: 

Path where to cache .osu files [/tmp/osumaps]: 

(Optional) To enable the -pp command you need to supply a path to PerformanceCalculator.dll.
    To get it you need to compile https://github.com/ppy/osu-tools.
Path to PerformanceCalculator.dll [none]: 

(Optional) Here you could supply your own beatmap api for star rating values, just leave this as-is cause it's unfortunately not open-source yet.
Beatmap API [https://osu.lea.moe]: 

(Required) A Discord bot token is required. You can create a bot here to receive one: https://discord.com/developers/applications/.
Discord bot token [none]: <my token>
/home/ubuntu/flowabot/node_modules/discord.js/src/client/ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (/home/ubuntu/flowabot/node_modules/discord.js/src/client/ClientDataManager.js:81:36)
    at Guild.setup (/home/ubuntu/flowabot/node_modules/discord.js/src/structures/Guild.js:307:68)
    at GuildCreateHandler.handle (/home/ubuntu/flowabot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (/home/ubuntu/flowabot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (/home/ubuntu/flowabot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (/home/ubuntu/flowabot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:299:17)
    at WebSocket.onMessage (/home/ubuntu/flowabot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/ubuntu/flowabot/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:198:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flowabot@1.0.0 config: `node generate-config`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flowabot@1.0.0 config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-04-04T15_16_07_664Z-debug.log
ubuntu@flowabot-423651:~/flowabot$
```

</details>

**Comment by KeepSOBP** [comment]
Fixed in  #52
